spring.application.name=file-sharing-backend
spring.profiles.active=dev
logging.level.root=INFO
logging.level.com.example.proiect_awbd=DEBUG
minio.url=http://localhost:9000
minio.access.name=minioadmin
minio.access.secret=minioadmin123
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
admin.username=${ADMIN_USERNAME:admin}
admin.password=${ADMIN_PASSWORD:changeme}
admin.email=${ADMIN_EMAIL:admin@example.com}
app.jwt.secret=aVeryLongSecretKeyThatIsAtLeast32CharactersLong1234567890abcdef
